import Foundation

@MainActor
func runAllTests() async throws {
    runAIVisualActionDomainTests()
    runAIVisualActionParserTests()
    runAIVisualActionPolicyTests()
    runAIVisualActionCoordinatorTests()
    runAIVisualActionMediatorTests()
    runAIVisualQuotaStoreTests()
    runAIVisualRateLimiterTests()
    runAIVisualDiagnosticsStoreTests()
    runActionIdTests()
    runActionRoleTests()
    runActionTagTests()
    runPetActionCatalogTests()
    runActionFallbackResolverTests()
    runIdleBehaviorPoolTests()
    runUniformIdleBehaviorSchedulerTests()
    runLegacyAnimationsAdapterTests()
    runPetActionCatalogBuilderTests()
    runPetEngineTests()
    runPetEngineActionDispatchTests()
    runPetEngineWeightedSchedulingTests()
    runPetEngineCommandHandlerActionsTests()
    runActionTriggerServiceTests()
    runActionsMenuBuilderTests()
    runMenuBarControllerActionsTests()
    runMenuBarControllerCompanionshipTests()
    runPetContextMenuBuilderTests()
    runMoodModelTests()
    runMoodLevelClassifierTests()
    runTimeOfDayClassifierTests()
    runMoodSnapshotProviderTests()
    runAfterTagStateTests()
    runTagConditionEvaluatorTests()
    runWeightedActionSamplerTests()
    runWeightedIdleBehaviorSchedulerTests()
    runAnimationPlayerTests()
    runScreenGeometryTests()
    runPreferencesStoreTests()
    runPreferencesStoreCustomPetTests()
    runPetPackageManifestTests()
    runPetPackageManifestSchemaV2Tests()
    runActionCodableTests()
    runSpriteFrameCodableTests()
    runActionPackManifestTests()
    runActionPackValidatorTests()
    runActionPackStoreTests()
    runActionPackWriterTests()
    runActionPackOverrideStoreTests()
    runActionPackOverrideMutationTests()
    runActionPackCatalogComposerTests()
    runActionImageNormalizerTests()
    runActionGridAnalyzerTests()
    runActionPackDraftBuilderTests()
    runActionImagePromptTemplateTests()
    runMultiAssetSpriteSheetRendererTests()
    runPetLibraryStoreActionPackTests()
    runPetLibraryCommanderActionPackTests()
    runActionPackImportWizardViewModelTests()
    runActionLibraryViewModelActionPackTests()
    runActionsMenuBuilderActionPackTests()
    runAIVisualActionPackBridgeTests()
    runActionPackSourceMetadataSanitizationTests()
    runPetPackageExporterActionPackTests()
    runPetPackageImporterActionPackTests()
    runPetPackageLoaderCompatibilityTests()
    runPetdexManifestParserTests()
    runPetdexArchiveReaderTests()
    runPetdexSpriteSheetProcessorTests()
    runPetdexAnimationMappingProviderTests()
    runPetdexAnimationMappingProviderActionsTests()
    runPetdexExtraRowInferrerTests()
    runPetdexGracefulSynthesizerTests()
    runPetdexPackageConverterTests()
    runPetdexPackageConverterActionsTests()
    runPetdexPackageImporterTests()
    runPetdexPackageImporterActionsTests()
    runPetdexPackageSelectingTests()
    runPetdexURLResolverTests()
    runPetdexDownloaderTests()
    runPetDefinitionCompatibilityTests()
    runPetDefinitionCatalogTests()
    runMotionProfileTests()
    runBubbleProfileTests()
    runPetPackageLoaderTests()
    runPetPackageImporterTests()
    runPetLibraryStoreTests()
    runPetLibraryStoreActionsTests()
    runPetActionOverrideStoreTests()
    runManifestRewriterTests()
    runPetActionOverrideStoreSchemaUpgradeTests()
    runPetLibraryPetdexTests()
    runPetLibraryPetdexSourceTests()
    runPetImageImporterTests()
    runPetLibraryManifestWriterTests()
    runSingleImageRendererTests()
    runSpriteSheetRendererTests()
    runPetRenderableFactoryTests()
    runPetViewRenderingTests()
    runPetOverlayImageCacheTests()
    runPetVisualStateControllerTests()
    runMotionProviderTests()
    runPetMotionEffectTests()
    runBubblePhraseProviderTests()
    runBubbleSchedulerTests()
    runBubbleEngineTests()
    runBubbleEngineCompanionshipTests()
    runBubblePhraseCatalogBuilderTests()
    runBubbleProfileCompatibilityTests()
    runContextualBubblePhraseProviderTests()
    runRelationshipLevelTests()
    runRelationshipStateTests()
    runInteractionSummaryTests()
    runRelationshipStoreTests()
    runRelationshipRuleTests()
    runRelationshipServiceTests()
    runRelationshipResetTests()
    runMicroDialogTests()
    runMicroDialogServiceTests()
    runMicroDialogRuleCatalogTests()
    runCompanionPreferencesStoreTests()
    runQuietModePolicyTests()
    runQuietModeSettingsViewModelTests()
    runCompanionEventTests()
    runCompanionContextTests()
    runCompanionTimeSlotTests()
    runCompanionEventRouterTests()
    runCompanionContextProviderTests()
    runCompanionshipSettingsViewModelTests()
    runPetWindowLayoutTests()
    runPetHitTestViewTests()
    runPetBubbleViewTests()
    runActionLibraryViewModelTests()
    runActionEditorViewModelTests()
    runImportWizardViewModelTests()
    runPetLibraryViewModelTests()
    runPetImportViewModelTests()
    runPetImportViewModelPetdexTests()
    runPetdexURLImportViewModelTests()
    runPetImageSelectingTests()
    runSettingsCustomPetTests()
    runSettingsPetdexTests()
    runSettingsPetdexURLTests()
    runAppCoordinatorActionsTests()
    runAppCoordinatorCompanionshipTests()
    runAppCoordinatorAICompanionTests()
    runCompanionNicknameTests()
    runAppCoordinatorCustomPetTests()
    runPetContextMenuMicroDialogTests()
    runAppCoordinatorMicroDialogTests()
    runAppCoordinatorPetdexTests()
    runAppCoordinatorPetdexURLTests()
    runPetLibraryCommanderPetdexTests()
    runCustomPetErrorHandlingTests()
    runPetdexErrorHandlingTests()
    runDesktopPetLogCustomCategoriesTests()
    runDesktopPetLogPetdexTests()
    runBubbleSafetyValidatorTests()
    runDefaultBubblePhraseSafetyTests()
    try await runAIProviderTests()
    runAIProviderRegistryTests()
    runAIProviderConfigTests()
    runAIRiskClassifierTests()
    runAISafetyServiceTests()
    runAIMemoryFilterTests()
    runAIMemoryStoreTests()
    runMemoryModule1Tests()
    runMemoryModule2Tests()
    runMemoryModule3Tests()
    runAIMemoryExporterTests()
    runAIPersonalityProfileTests()
    runAIPromptComposerTests()
    runAIPersonalityEngineTests()
    try await runAIChatEngineTests()
    runAIChatSessionTests()
    runAIChatContextBuilderTests()
    runAIChatBubbleAdapterTests()
    runAIBubbleBridgeTests()
    runChatPanelControllerTests()
    await runChatPanelViewModelTests()
    runAICompanionPreferencesTests()
    await runAICompanionPreferencesStoreTests()
    runAIMemoryViewModelTests()
    runAISettingsViewModelTests()
    runContentPackValidatorTests()
    runContentPackManagerTests()
    runDialoguePackTests()
    runPersonalityPackTests()
    runActionPackTests()
    runContentPackViewModelTests()
    runAppCoordinatorContentPackTests()
    runInputEventMapperTests()
    runInputSyncServiceTests()
    runActivityZoneTests()
    runScreenBoundaryDetectorTests()
    runSpatialBehaviorEngineTests()
    runDesktopSpaceServiceTests()
    runEventActionMappingTests()
    runExternalConnectionManagerTests()
    runExternalStateServiceTests()
    runAdvancedPreferencesTests()
    runAdvancedPreferencesStoreTests()
    runInteractiveBubbleSchedulerTests()
    runInteractiveBubblePresenterTests()
    runInteractiveBubbleViewTests()
    runInteractiveBubbleSettingsStoreTests()
    runInteractiveBubbleSettingsViewTests()
    runStaticPhraseLibraryTests()
    await runInteractiveBubbleContentGeneratorTests()
    await runInteractiveBubbleContentGeneratorAITests()
    runInteractiveBubbleOptionHandlerTests()
    runAIVisualSafetyServiceTests()
    runAIVisualPromptSanitizerTests()
    runVisualGenerationRequestTests()
    runVisualGenerationCapabilitiesTests()
    runVisualGenerationProviderRegistryTests()
    try await runVisualGenerationServiceTests()
    runMiniMaxCLIQuotaParserTests()
    try await runMiniMaxCLIImageGeneratorTests()
    runPetVisualAssetStoreTests()
    runPetReferenceImageProviderTests()
    try await runGenerationDiagnosticsStoreTests()
    try await runPetIdentityDescriptorStoreTests()
    try await runPromptStrategyTests()
    try await runReferenceImagePipelineTests()
    try await runQualityGateStoreTests()
    try await runAssetLifecycleManagerTests()
    try await runPreviewPresenterTests()
    try await runUserFeedbackStoreTests()
    try await runConsistencyPreferenceStoreTests()
    runAIVisualSettingsViewModelTests()
    runAIVisualHistoryViewModelTests()
    runPetVisualPreferenceStoreTests()
    runPetVisualHistoryStoreTests()
    try await runAPIProviderImageGeneratorTests()
    try await runMiniMaxCLIVideoGeneratorTests()
    try runVisualVideoExperimentStoreTests()
}

try await runAllTests()
print("DesktopPetUnitTests passed")
